server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.32.130:3306/cloud_order?useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 192.168.32.130:8848
      discovery:
        cluster-name: CD
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
# ribbon饥饿加载
#ribbon:
#  eager-load:
#    enabled: true
#    clients: userService
# feign日志功能
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: HEADERS
# 开启使用httpclient作为feign的底层实现
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50