server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mnsx/SpringCloud-StudyProject.git
          search-paths:
            - springcloud-config
          username: Mnsx
          password: xkq771212XKQ
          skip-ssl-validation: true
      label: master
  rabbitmq:
    host: 192.168.32.129
    port: 5672
    username: root
    password: 123123
    virtual-host: center

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'